### ISSUE TITLE
Changes are not reflected in the docker container

### ISSUE THREAD

**Issue by HJassar** [GeekyAnts/express-typescript#13]
When I make any changes in the `/controller` directory, they do not get reflected in the api request itself
example: changed under /controllers/Api/Home.ts
```typescript
class Home {
  public static index(req, res, next): any {
    return res.json({
      message: "hi", // Locals.config().name,
    });
  }
}
```
but the API response is still the name of the app not "hi" unless I restart the docker container.

**Comment by faizahmedfarooqui** [comment]
Yes, you need to re-create the build if you're running your app in production after making changes. Check the "script" index of the package.json file. It will help.

**Comment by HJassar** [comment]
Thank you so much for the prompt response. How do I run it in dev in **docker**?
I tried changing this
```
#Build to project
RUN npm run build

# Run node server
CMD npm run start
```
to this
```
# Run node server
CMD npm run dev
```
Basically what I'm trying to do is not have to restart the container every time I make a change so that I can test the changes.

**Comment by faizahmedfarooqui** [comment]
@HJassar There are lots of resources available on internet where they specifically explain us on how to run docker + node’s dev environment. 

Essentially you should be looking for docker-compose. It is how we most of the time end up using our node app in dev environment. 

I’d recommend though to use nodemon on your local machine directly for development.

**Comment by HJassar** [comment]
Thank you so very much for the clarification. Appreciate it!
