### ISSUE TITLE
Error: `useCreateIndex` is an invalid option.

### ISSUE THREAD

**Issue by CeoFred** [GeekyAnts/express-typescript#19]
**Describe the bug**
The app fails to run or start a connection to a mongodb url because of a deprecated option being set.

**To Reproduce**
1. run ``` yarn dev ``` or ``` npm run dev ```

**Expected behavior**
The Application fails to start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 12.5

**Smartphone (please complete the following information):**
N/A

**Additional context**
For versions of Mongoose >= 6, setting `useCreateIndex` is invalid, and this boilerplate uses >=6.4.6

**Comment by faizahmedfarooqui** [comment]
@CeoFred I've updated our codebase with the latest changes. Please review & confirm.

**Comment by CeoFred** [comment]
GREAT!
