### ISSUE TITLE
**/node_modules/@types/mongoose/index.d.ts' not found

### ISSUE THREAD

**Issue by bannarisoftwares** [GeekyAnts/express-typescript#6]
**Describe the bug**
Getting `error TS6053: File '/Users/**/node_modules/@types/mongoose/index.d.ts' not found. while starting npm run dev

[06:19:09] Found 1 error. Watching for file changes.`

**To Reproduce**
1. Clone the repo and do npm i
2. Do npm run dev

**Expected behavior**
Should start without error

**Comment by HardikKSavaliya** [comment]
it is due to an @types/mongoose being unavailabe and not able to install.

**Comment by linhnvg** [comment]
I have idea, you down version mongoose to 5.11.15 and add GOOGLE_ID, TWITTER_KEY in .env
